---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# Kubernetes-enabled component example
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-k8s-app
  annotations:
    backstage.io/kubernetes-id: my-k8s-app
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: 'app=my-k8s-app'
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---
# Backstage Pod component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-pod-component
  annotations:
    backstage.io/kubernetes-id: backstage-pod
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: 'run=backstage-pod'
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---
# Cluster-wide resource viewer - shows ALL resources in default namespace
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: local-cluster-viewer
  title: "Local Kubernetes Cluster"
  description: "View all resources in your local minikube cluster"
  annotations:
    backstage.io/kubernetes-id: cluster-viewer
    backstage.io/kubernetes-namespace: default
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
