---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  namespace: default
  labels:
    app: my-k8s-app
    backstage.io/kubernetes-id: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        backstage.io/kubernetes-id: my-k8s-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app-service
  namespace: default
  labels:
    app: my-k8s-app
    backstage.io/kubernetes-id: my-k8s-app
spec:
  selector:
    app: my-k8s-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP